default:
  extensions: 
    - ".csv"
    - ".xlsx"
    - ".xlsx"
    - ".txt"
  PATHS:
    DATA_PATH : "./data/"
    OUT_PATH : "./{dir}/outputs/"
    FIG_PATH : "./{dir}/figures/"
    SCRIPTS_PATH : "./{dir}/scripts/"
    UTILS_PATH : "./{dir}/scripts/"
    PLOT_PATH : "./plots/"
    PLOT_STYLE : "./plots/plot_style.mplstyle"
  MODELS:
    SEED : 4321
    ITER : 2000
    CHAINS : 4
    MIN_VAL : 0
    MAX_VAL: 130
  WAVES:
    ROOTS: 
      - 1
      - 3
      - 6
      - 8
      - 8
      - 10
      - 11
      - 13
    GAUSSIAN_KERNEL: 10
  UPDATE_DATES:
    GENOMICS : "20220802"